const contentRu = {
    elMenu1: "Донат",
    elMenu2: "Блог",
    elMenu3: "Контакты",
    elMenu4: "О нас",
    contentDes: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio provident veniam, quaerat accusantium tempore placeat perspiciatis natus reprehenderit veritatis sint magnam unde. Atque quas consequuntur quis accusantium expedita beatae perferendis. Numquam nam alias, exercitationem similique facere quos provident sapiente fugiat voluptatem impedit maiores? Earum, molestias nesciunt, accusamus nulla cum alias accusantium doloribus ipsum maiores eaque aut pariatur repudiandae in neque.",
    card1: "Lorem ipsum dolor sit amet",
    card2: "Lorem ipsum dolor sit amet",
    card3: "Lorem ipsum dolor sit amet",
    playlistTitle: "Сейчас играет",
    playlistList: "Проигранные треки",
    project: "наши проекты",
    projectTitleOne: "Зависимые от вайба",
    projectTitleTwo: "Дембоу",
    projectTitleThree: "Вселенная Рэгги",
    projectTitleFour: "Женщины в Рэгги",
    projectOne: "Информационный ресурс о Рэгги-музыке и её истоках, культуре Ямайки и движении Растафарай",
    projectTwo: "Самый беззаботный ресурс рунет о карибской танцевальной музыке",
    projectThree: "Паблик, специализирующийся на эксклюзивной выкладке тех Рэгги-альбомов, которых ещё нет в вк. Наш девиз - для этой музыки нет границ, поэтому мы постим музыку всех стран и континентов",
    projectFour: "Тематическая группа о вкладе женщин в становление Рэгги-музыки и смежных карибских стилей, а также их роли в современном развитии этих направлений",
    more: "Подробнее",
    broadcast: "нас вещают",
    feedTitle: "Обратная связь",
    feedName: "имя",
    feedComent: "коммент",
    feedProposal: "Ваш адрес email не будет опубликован. Обязательные поля помечены",
    feedBtn: "Отправить",
    feedExpl: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus aspernatur quidem officia assumenda cumque labore eligendi nobis quo veniam quam, omnis facere repellat sequi minus enim! Qui dignissimos aut quis?",
    feedFile: "Прикрепить файл"
};

const contentEn = {
    elMenu1: "Donat",
    elMenu2: "The blog",
    elMenu3: "Contacts",
    elMenu4: "About us",
    contentDes: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio provident veniam, quaerat accusantium tempore placeat perspiciatis natus reprehenderit veritatis sint magnam unde. Atque quas consequuntur quis accusantium expedita beatae perferendis. Numquam nam alias, exercitationem similique facere quos provident sapiente fugiat voluptatem impedit maiores? Earum, molestias nesciunt, accusamus nulla cum alias accusantium doloribus ipsum maiores eaque aut pariatur repudiandae in neque.",
    card1: "Lorem ipsum dolor sit amet",
    card2: "Lorem ipsum dolor sit amet",
    card3: "Lorem dolor sit amet",
    playlistTitle: "Now playing",
    playlistList: "Recently played tracks",
    project: "our projects",
    projectTitleOne: "Dependent on vibe",
    projectTitleTwo: "Dembou",
    projectTitleThree: "The Reggae Universe",
    projectTitleFour: "Women in Reggae",
    projectOne: "An information resource about Reggae music and its origins, Jamaican culture and the Rastafarian movement",
    projectTwo: "The most carefree runet resource about Caribbean dance music",
    projectThree: "A public specializing in the exclusive distribution of those Reggae albums that are not yet in the VK. Our motto is that there are no borders for this music, so we post music from all countries and continents",
    projectFour: "Thematic group on the contribution of women to the formation of Reggae music and related Caribbean styles, as well as their role in the modern development of these areas",
    more: "More",
    broadcast: "we are being broadcast",
    feedTitle: "Feedback",
    feedName: "name",
    feedComent: "comment",
    feedProposal: "Your email address will not be published. Required fields are marked",
    feedBtn: "Send",
    feedExpl: "Lorem ipsum dolor. Accusamus aspernatur quidem officia assumenda cumque labore eligendi nobis quo veniam quam, omnis facere repellat sequi minus enim! Qui dignissimos aut quis?",
    feedFile: "Attach a file"
};

export {
    contentRu,
    contentEn
};