const contentRu = {
    elMenu1: "Донат",
    elMenu2: "Регги Блог",
    elMenu3: "Контакты",
    elMenu4: "О нас",
    contentDes: "Рэгги-Вселенная - первое и единственное онлайн-радио в России, которое вещает Рэгги, Даб и Дансхол. Мы стартовали как публичная страница в соцсети vk с целью способствовать популяризации любимой нами регги музыки там, где её почти никто не слушал. Со временем пришла шальная идея запустить онлайн-радио, в успех которого даже мы сами до конца толком не верили. Сегодня же нас слушает уже вся планета! Во многом потому, что мы верим в универсальный, вселенский характер Рэгги - зародившаяся на Ямайке музыка давно перешагнула все границы и стала глобальным феноменом. В нашем эфире Вы можете слушать Регги со всех уголков света и на всех языках - бесплатно и безо всякой рекламы в эфире. Только музыка!",
    card1: "Проект запущен в 2014, а радио в эфире с 2018.",
    card2: "Lorem ipsum dolor sit amet",
    card3: "Lorem ipsum dolor sit amet",
    playlistTitle: "Сейчас играет",
    playlistList: "Проигранные треки",
    project: "наши проекты",
    projectTitleOne: "Зависимые от вайба",
    projectTitleTwo: "Дембоу",
    projectTitleThree: "Вселенная Рэгги",
    projectTitleFour: "Женщины в Рэгги",
    projectOne: "Информационный ресурс о Рэгги-музыке и её истоках, культуре Ямайки и движении Растафарай",
    projectTwo: "Самый беззаботный ресурс рунет о карибской танцевальной музыке",
    projectThree: "Паблик, специализирующийся на эксклюзивной выкладке тех Рэгги-альбомов, которых ещё нет в вк. Наш девиз - для этой музыки нет границ, поэтому мы постим музыку всех стран и континентов",
    projectFour: "Тематическая группа о вкладе женщин в становление Рэгги-музыки и смежных карибских стилей, а также их роли в современном развитии этих направлений",
    more: "Подробнее",
    broadcast: "нас вещают",
    feedTitle: "Обратная связь",
    feedName: "имя",
    feedComent: "коммент",
    feedProposal: "Обязательные поля помечены",
    feedBtn: "Отправить",
    feedExpl: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus aspernatur quidem officia assumenda cumque labore eligendi nobis quo veniam quam, omnis facere repellat sequi minus enim! Qui dignissimos aut quis?",
    feedFile: "Прикрепить файл",
    feedPolitical: "Я соглашаюсь с",
    feedPoliticalLink: "Политикой в отношении обработки персональных данных",
};

const contentEn = {
    elMenu1: "Donat",
    elMenu2: "Reggae Blog",
    elMenu3: "Contacts",
    elMenu4: "About us",
    contentDes: "Radio Reggae Universe is the first and only online radio in Russia that plays Reggae, Dub and Dancehall. We began our journey on VK (Russian social media platform). Our goal was to promote our favorite music locally. Over time we decided to launch the online radio. In the beginning nobody believed that it would be a successful project. And nowadays the whole planet Earth is jamming to our vibes. We believe in global and universal nature of Reggae music. Thats why we play Reggae from every part of the World in any language. The broadcast is free and without any advertisements! Only Music! Tune up :)",
    card1: "The project was launched in 2014. The radio has been on air since 2018. ",
    card2: "Lorem ipsum dolor sit amet",
    card3: "Lorem dolor sit amet",
    playlistTitle: "Now playing",
    playlistList: "Recently played tracks",
    project: "our projects",
    projectTitleOne: "Vibes Addict",
    projectTitleTwo: "Dembow",
    projectTitleThree: "The Reggae Universe",
    projectTitleFour: "Female Reggae",
    projectOne: "An information resource about Reggae music and its origins, Jamaican culture and the Rastafarian movement",
    projectTwo: "The most carefree runet resource about Caribbean dance music",
    projectThree: "A public specializing in the exclusive distribution of those Reggae albums that are not yet in the VK. Our motto is that there are no borders for this music, so we post music from all countries and continents",
    projectFour: "Thematic group on the contribution of women to the formation of Reggae music and related Caribbean styles, as well as their role in the modern development of these areas",
    more: "More",
    broadcast: "we are being broadcast",
    feedTitle: "Feedback",
    feedName: "name",
    feedComent: "comment",
    feedProposal: "Required fields are marked",
    feedBtn: "Send",
    feedExpl: "Lorem ipsum dolor. Accusamus aspernatur quidem officia assumenda cumque labore eligendi nobis quo veniam quam, omnis facere repellat sequi minus enim! Qui dignissimos aut quis?",
    feedFile: "Attach a file",
    feedPolitical: "I agree with",
    feedPoliticalLink: "Personal data processing policy",
};

export {
    contentRu,
    contentEn
};