"use strict"
import './_click-language.js'
import './_player.js';
import './_slider.js';
import './_our-projects.js';
import './_footer-year.js';
import './_animation.js';
import './_policy.js';
import './_adaptive.js';